import { Solver } from "./d08";

const example = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

describe("d08 Solver", () => {
  it("should solve part 1 examples", () => {
    const solver = new Solver(example);
    expect(solver.part1()).toBe(14);
  });

  it("should solve part 2 examples", () => {
    const solver = new Solver(example);
    expect(solver.part2()).toBe(34);
  });
});
