#!/usr/bin/env bash
newest="$(ls c*.py | grep -Eo 'c([0-9]+)\.py' | grep -Eo '[0-9]+' | sort -n | tail -n 1 | awk '{printf "%02d\n", $1 + 1}')"
cp c00.py "c${newest}.py"
cp c00_test.py "c${newest}_test.py"
